hmpps.sqs:
  provider: localstack
  queues:
    datacompliancerequest:
      queueName: data_compliance_request_queue
      dlqName: data_compliance_request_queue_dlq
    datacomplianceresponse:
      queueName: data_compliance_response_queue
      dlqName: data_compliance_response_queue_dlq
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:hmpps_domain_events