hmpps.sqs:
  provider: localstack
  queues:
    datacompliancerequest:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    datacomplianceresponse:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
  topics:
    datacomplianceevents:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}