server:
  shutdown: immediate

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

api.base.url.oauth: http://localhost:8090/auth

spring:
  main:
    allow-bean-definition-overriding: true

data.compliance:
  deletion.enabled: true
  deceased.deletion.enabled: true
  offender.no.booking.deletion.enabled: true

server.shutdown: immediate
