server:
  shutdown: immediate

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

api:
  base:
    url:
      oauth: http://localhost:8090/auth

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/dev

  devtools:
    add-properties: true

  datasource:
    url: 'jdbc:h2:mem:nomis-db;MODE=Oracle'

  jpa:
    show-sql: true
