---
# Per environment values which override defaults in nomis-prisoner-deletion-service/values.yaml

generic-service:
  replicaCount: 2

  poddisruptionbudget:
    enabled: true
    minAvailable: 1

  ingress:
    host: nomis-delete.aks-dev-1.studio-hosting.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    DATA_COMPLIANCE_DELETION_ENABLED: false
    DATA_COMPLIANCE_DECEASED_DELETION_ENABLED: false
    DATA_COMPLIANCE_OFFENDER_NO_BOOKING_DELETION_ENABLED: false