---
generic-service:
  nameOverride: nomis-prisoner-deletion-service

  replicaCount: 4

  image:
    repository: quay.io/hmpps/nomis-prisoner-deletion-service
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: nomis-prisoner-deletion-service-cert
    path: /

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "oracle"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    nomis-prisoner-deletion-service:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      JDBC_URL: "JDBC_URL"
      DB_USERNAME: "DB_USERNAME"
      DB_PASSWORD: "DB_PASSWORD"


  allowlist: null
